version: '3.8'

services:
  # Servi√ßo de Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: anime_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Porta Externa : Porta Interna
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistir dados se desligar o container
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script para criar tabelas no arranque

volumes:
  postgres_data: